2016-08-30 10:29:44.454 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:31:35.395 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:32:25.809 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:33:00.095 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:33:39.934 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:34:30.982 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:35:41.520 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:38:59.681 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:39:32.363 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:40:20.369 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:40:57.531 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:41:16.156 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:43:53.971 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:44:17.881 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:45:36.555 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:46:18.309 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-30 10:47:14.557 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-31 10:28:02.055 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-31 10:29:10.836 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-08-31 15:12:27.208 [error] <0.210.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.215.0> exit with reason normal in context child_terminated
2016-08-31 15:12:27.481 [error] <0.262.0> CRASH REPORT Process <0.262.0> with 0 neighbours exited with reason: no match of right hand value {error,econnrefused} in 'Elixir.ElixirThrift.Receiver':init/1 line 2 in gen_server:init_it/6 line 352
2016-08-31 15:12:27.482 [error] <0.261.0> Supervisor 'Elixir.ElixirThrift.Supervisor' had child 'Elixir.ElixirThrift.Receiver' started with 'Elixir.ElixirThrift.Receiver':start_link() at undefined exit with reason no match of right hand value {error,econnrefused} in 'Elixir.ElixirThrift.Receiver':init/1 line 2 in context start_error
2016-08-31 15:12:27.482 [error] <0.259.0> CRASH REPORT Process <0.259.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.ElixirThrift.Receiver',{{badmatch,{error,econnrefused}},[{'Elixir.ElixirThrift.Receiver',init,1,[{file,"lib/elixir_thrift/receiver.ex"},{line,2}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}},{'Elixir.ElixirThrift',start,[normal,[]]}} in application_master:init/4 line 134
2016-08-31 15:13:54.626 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:13:54.882 [error] <0.203.0> CRASH REPORT Process <0.203.0> with 0 neighbours exited with reason: no match of right hand value {error,econnrefused} in 'Elixir.Tackle':publish/2 line 10 in application_master:init/4 line 134
2016-08-31 15:15:20.441 [error] <0.144.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.149.0> exit with reason normal in context child_terminated
2016-08-31 15:18:22.077 [error] <0.210.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.215.0> exit with reason normal in context child_terminated
2016-08-31 15:18:22.233 [error] <0.259.0> CRASH REPORT Process <0.259.0> with 0 neighbours exited with reason: struct_unmatched in thrift_protocol:write/2 line 334 in application_master:init/4 line 134
2016-08-31 15:19:48.059 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:22:20.396 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:22:37.007 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:22:37.172 [error] <0.203.0> CRASH REPORT Process <0.203.0> with 0 neighbours exited with reason: struct_unmatched in thrift_protocol:write/2 line 334 in application_master:init/4 line 134
2016-08-31 15:23:56.063 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:23:56.220 [error] <0.203.0> CRASH REPORT Process <0.203.0> with 0 neighbours exited with reason: struct_unmatched in thrift_protocol:write/2 line 334 in application_master:init/4 line 134
2016-08-31 15:25:26.914 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:25:27.273 [error] <0.203.0> CRASH REPORT Process <0.203.0> with 0 neighbours exited with reason: struct_unmatched in thrift_protocol:write/2 line 334 in application_master:init/4 line 134
2016-08-31 15:28:21.659 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:32:58.202 [error] <0.160.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.165.0> exit with reason normal in context child_terminated
2016-08-31 15:33:20.154 [error] <0.144.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.149.0> exit with reason normal in context child_terminated
2016-08-31 15:33:36.261 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:33:59.078 [error] <0.154.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.159.0> exit with reason normal in context child_terminated
2016-08-31 15:33:59.227 [error] <0.203.0> CRASH REPORT Process <0.203.0> with 0 neighbours exited with reason: bad argument in thrift_binary_protocol:write/2 line 149 in application_master:init/4 line 134
